"""The front door, and the four ways it could quietly stop being true.

`docs/index.html` is generated by `scripts/build_site.py` from two files in the
repository: the captured demo transcript and a real slice of an audit chain.
These tests exist because a page that drifts from those is worse than no page —
it is a claim that cannot be checked, attached to a project whose entire
argument is that everything can be.

The README has gone stale twice already (lesson 67) and nothing in CI noticed
either time. This is the same failure mode with a wider blast radius, because
the site is what a stranger sees first.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
SCRIPT = ROOT / "scripts" / "build_site.py"
PAGE = ROOT / "docs" / "index.html"
TRANSCRIPT = ROOT / "docs" / "demo" / "attack.txt"
DECISIONS = ROOT / "docs" / "decisions"

SMALLEST_PLAUSIBLE_PAGE = 8_000

ADR_HREF = re.compile(r'href="[^"]*/docs/decisions/(?P<name>\d{4}-[^"]+\.md)"')
DATA_BLOCK = re.compile(
    r'<script id="site-data" type="application/json">(?P<json>.*?)</script>', re.DOTALL
)


@pytest.fixture(scope="module")
def page() -> str:
    if not PAGE.exists():
        pytest.fail(f"{PAGE} is missing. Run: make site")
    return PAGE.read_text(encoding="utf-8")


def test_the_page_exists_and_is_not_a_stub(page: str) -> None:
    """LESSON 65 — the premise, before anything that depends on it.

    Every assertion below would pass vacuously against an empty file or a
    half-written one.
    """
    assert len(page) > SMALLEST_PLAUSIBLE_PAGE
    assert page.startswith("<!doctype html>")


def test_the_page_is_up_to_date_with_its_inputs() -> None:
    """THE ONE THAT MATTERS.

    Regenerates the page and compares. If the transcript is recaptured, the
    chain slice replaced, or the builder changed, and nobody re-ran `make site`,
    this fails — rather than the site silently showing last month's run.
    """
    result = subprocess.run(  # noqa: S603
        [sys.executable, str(SCRIPT), "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_the_page_carries_the_transcript_verbatim(page: str) -> None:
    """The replay is the captured file, not a retelling of it.

    Checked through the embedded JSON rather than by searching the HTML,
    because the terminal is rendered from that block at run time — so this
    tests what a visitor actually sees.
    """
    match = DATA_BLOCK.search(page)
    assert match is not None, "the page has no embedded data block"

    data = json.loads(match.group("json").replace("<\\/", "</"))
    assert data["transcript"] == TRANSCRIPT.read_text(encoding="utf-8").rstrip("\n")


def test_every_decision_the_page_links_exists(page: str) -> None:
    """LESSON 66, in HTML this time.

    A browser renders a 404 link exactly as well as a live one, and the page
    links roughly thirty decision records by filename.
    """
    names = {match.group("name") for match in ADR_HREF.finditer(page)}
    assert names, "the page links no decision records at all"

    missing = sorted(name for name in names if not (DECISIONS / name).exists())
    assert not missing, f"the page links to decision records that do not exist: {missing}"


def test_the_page_reports_the_outcome_that_actually_happened(page: str) -> None:
    """THE HONESTY TEST, and the reason this file is worth its length.

    Every incentive points at a front page where the firewall wins. It did not
    win: it detected the attack at high confidence and was not permitted to act,
    and a human stopped the exfiltration.

    If somebody later edits this page into the flattering version, it will
    contradict `make attack-demo` on the reader's own machine — which converts
    the project's one real asset, that everything here is checkable, into
    evidence of the opposite. So the honest sentence is asserted.
    """
    # Whitespace-collapsed, because HTML collapses it and the source is wrapped
    # to 100 columns. Asserting the byte sequence would make this test fail for
    # a reflow, which trains somebody to weaken it.
    prose = " ".join(page.split())
    assert "was not allowed to stop it" in prose
    assert "measured into silence" in prose


def test_the_page_states_what_the_project_does_not_do(page: str) -> None:
    """On the page rather than buried, because it is the most credible thing on
    it — and the first thing an editor optimising for impact would remove."""
    assert "What it does not do" in page
    assert "It does not stop prompt injection" in page
