#!/usr/bin/env python3
"""Import BIPIA's contexts and attack instructions as a training and evaluation corpus.

    git clone https://github.com/microsoft/BIPIA /tmp/bipia
    git -C /tmp/bipia checkout a004b69ec0dd446e0afd461d98cb5e96e120a5d0
    uv run python scripts/import_bipia.py --from /tmp/bipia

Writes `corpus/external/bipia/documents.jsonl`, `heldout.txt`, `LICENCE` and
`NOTICE.txt`, and the evasion corpus v1 built from the sealed test attacks,
`corpus/external/evasion/documents.jsonl`. Byte-identical on every run. The construction rule is
`acp.corpus.bipia`; the split is BIPIA's own (ADR 0074).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from acp.corpus.bipia import (
    CODE_TASK,
    SPLITS,
    TABLE_CONTEXTS,
    Context,
    build,
    default_bipia_dir,
    dump,
    instructions_from,
)
from acp.corpus.evasion import disguise

COMMIT = "a004b69ec0dd446e0afd461d98cb5e96e120a5d0"
HELDOUT_VERSION = 1


def contexts(source: Path, split: str) -> tuple[dict[str, list[Context]], list[Context]]:
    """The contexts that receive attacks, and the extra train tables that stay clean."""
    out: dict[str, list[Context]] = {}
    extra: list[Context] = []
    for task in ("email", "table", CODE_TASK):
        rows = [
            json.loads(line)
            for line in (source / "benchmark" / task / f"{split}.jsonl").read_text().splitlines()
            if line.strip()
        ]
        texts = [
            r["context"] if isinstance(r["context"], str) else "\n".join(r["context"]) for r in rows
        ]
        made = [Context(task, i, t.strip("\n")) for i, t in enumerate(texts)]
        if task == "table":
            made, rest = made[:TABLE_CONTEXTS], made[TABLE_CONTEXTS:]
            extra.extend(rest)
        out[task] = made
    return out, extra


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__ and __doc__.splitlines()[0])
    parser.add_argument("--from", dest="source", type=Path, required=True, help="a BIPIA checkout")
    args = parser.parse_args()
    source: Path = args.source

    docs = []
    test_attacked, test_extra = contexts(source, "test")
    test_texts = {c.text for group in (*test_attacked.values(), test_extra) for c in group}
    dropped = 0
    for split in SPLITS:
        bench = source / "benchmark"
        instructions = [
            *instructions_from(
                "text", json.loads((bench / f"text_attack_{split}.json").read_text())
            ),
            *instructions_from(
                "code", json.loads((bench / f"code_attack_{split}.json").read_text())
            ),
        ]
        attacked, extra = contexts(source, split)
        if split == "train":
            # BIPIA repeats some contexts across its splits; a train copy of a test
            # context would leak it, so train keeps only contexts the test lacks.
            before = sum(map(len, attacked.values())) + len(extra)
            attacked = {
                t: [c for c in cs if c.text not in test_texts] for t, cs in attacked.items()
            }
            extra = [c for c in extra if c.text not in test_texts]
            dropped = before - sum(map(len, attacked.values())) - len(extra)
        docs.extend(build(split, attacked, instructions, clean_only=extra))

    out = default_bipia_dir()
    out.mkdir(parents=True, exist_ok=True)
    (out / "documents.jsonl").write_text(dump(docs), encoding="utf-8", newline="\n")
    shutil.copyfile(source / "LICENSE", out / "LICENCE")
    shutil.copyfile(source / "NOTICE.md", out / "NOTICE.txt")

    sealed = sorted({d.group for d in docs if d.split == "test"})
    lines = [
        f"# Held-out split v{HELDOUT_VERSION} — BIPIA, its authors' test split.",
        "#",
        "# GENERATED by scripts/import_bipia.py; do not edit. Every document whose",
        "# `group` is listed here is SEALED: never trained on, never used to choose a",
        "# threshold, and scored once by scripts/evaluate_learned.py --unseal (ADR 0074).",
        "",
        f"version: {HELDOUT_VERSION}",
        "",
        *sealed,
        "",
    ]
    (out / "heldout.txt").write_text("\n".join(lines), encoding="utf-8")
    evasion = disguise([d for d in docs if d.split == "test"])
    evasion_dir = out.parent / "evasion"
    evasion_dir.mkdir(parents=True, exist_ok=True)
    (evasion_dir / "documents.jsonl").write_text(dump(evasion), encoding="utf-8", newline="\n")
    attacks = sum(d.label == "attack" for d in docs)
    print(f"{len(evasion)} evasion documents", file=sys.stderr)
    print(
        f"{len(docs)} documents ({attacks} attacks) from BIPIA {COMMIT[:7]}; "
        f"{dropped} train contexts dropped as copies of test contexts",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
