#!/usr/bin/env python3
"""Import AgentDojo's environments, injection vectors, goals and attack templates as a corpus.

    pip download --no-deps agentdojo==0.1.35 -d /tmp/ad
    uv run python scripts/import_agentdojo.py --wheel /tmp/ad/agentdojo-0.1.35-py3-none-any.whl

Reads the wheel as a zip (nothing is installed or executed) and writes
`corpus/external/agentdojo/documents.jsonl`, `heldout.txt` and `LICENCE`. The wheel's
SHA-256 is pinned; the output is byte-identical on every run. The construction rule is
`acp.corpus.agentdojo` (ADR 0079).
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import zipfile
from collections import Counter
from pathlib import Path
from typing import Final

import yaml

from acp.corpus.agentdojo import (
    SOURCE,
    SUITE_VERSIONS,
    SUITES,
    TEMPLATES,
    VERSION,
    Vector,
    build,
    goals,
    load_environment,
    module_constants,
)
from acp.corpus.bipia import ATTACK, dump
from acp.corpus.loader import default_root

WHEEL_SHA256: Final = "364bea4219716b716bf639f504d195943f7f6a5535d312ca41d7098704a2affd"
HELDOUT_VERSION: Final = 1
PACKAGE: Final = "agentdojo/"


def read(wheel: zipfile.ZipFile, name: str) -> str:
    return wheel.read(PACKAGE + name).decode("utf-8")


def check_templates(wheel: zipfile.ZipFile) -> None:
    """Every template, as this repository writes it, must appear in the pinned source."""
    source = "".join(
        read(wheel, f"attacks/{f}")
        for f in ("important_instructions_attacks.py", "baseline_attacks.py")
    )
    flattened = source.replace('"\n        "', "").replace('"\n            "', "")
    for name, template in TEMPLATES.items():
        literal = template.replace("\n", "\\n")
        if literal not in flattened:
            msg = f"template {name} does not appear in the pinned AgentDojo source"
            raise SystemExit(msg)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__ and __doc__.splitlines()[0])
    parser.add_argument("--wheel", type=Path, required=True)
    args = parser.parse_args()

    digest = hashlib.sha256(args.wheel.read_bytes()).hexdigest()
    if digest != WHEEL_SHA256:
        msg = f"wheel sha256 {digest} is not the pinned {WHEEL_SHA256}"
        raise SystemExit(msg)

    out = default_root() / "external" / SOURCE
    out.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.wheel) as wheel:
        check_templates(wheel)
        names = set(wheel.namelist())
        all_python = [
            read(wheel, n[len(PACKAGE) :])
            for n in sorted(names)
            if n.startswith(PACKAGE + "default_suites/") and n.endswith(".py")
        ]
        constants = module_constants(all_python)
        docs = []
        for suite in SUITES:
            modules = [
                (v, read(wheel, f"default_suites/{v}/{suite}/injection_tasks.py"))
                for v in SUITE_VERSIONS
                if f"{PACKAGE}default_suites/{v}/{suite}/injection_tasks.py" in names
            ]
            base = f"data/suites/{suite}/"
            environment = load_environment(
                read(wheel, base + "environment.yaml"),
                include=lambda rel, base=base: read(wheel, base + rel),
            )
            raw = yaml.safe_load(read(wheel, base + "injection_vectors.yaml"))
            vectors = [Vector(suite, k, str(v.get("default") or "")) for k, v in raw.items()]
            docs += build(suite, environment, vectors, goals(modules, constants))
        licence = wheel.read(f"agentdojo-{VERSION}.dist-info/licenses/LICENSE").decode("utf-8")

    (out / "documents.jsonl").write_text(dump(docs), encoding="utf-8")
    (out / "LICENCE").write_text(licence, encoding="utf-8")
    sealed = sorted({d.group for d in docs if d.split == "test"})
    (out / "heldout.txt").write_text(
        "# Held-out split v1 — AgentDojo, one goal in three and one injection vector in three.\n"
        "#\n"
        "# GENERATED by scripts/import_agentdojo.py; do not edit. Every document whose\n"
        "# `group` is listed here is SEALED: never trained on, never used to choose a\n"
        "# threshold, and scored once (ADR 0079).\n\n"
        f"version: {HELDOUT_VERSION}\n\n" + "".join(f"{g}\n" for g in sealed),
        encoding="utf-8",
    )
    counts = Counter((d.split, d.label) for d in docs)
    templates = Counter(d.category for d in docs if d.label == ATTACK)
    print(f"{len(docs)} documents: {dict(sorted(counts.items()))}", file=sys.stderr)
    print(f"templates: {dict(sorted(templates.items()))}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
